### PR TITLE
Setup transpilation from ES6 to ES5, and rewrite in ES6

### PR DESCRIPTION
**Pull request by amyboyd**
Saves 8 lines. Also it looks cooler.

### CODE REVIEW

**Comment by amyboyd** [comment]
@partnermarketing/developers Thoughts?

**Comment by amyboyd** [comment]
(Yes this really is from January)

**Comment by BernardoSilva** [comment]
Let's try to finish issue https://github.com/partnermarketing/angular-same-height-directive/issues/2 before merging this one.

Once this one is merged we can bump the release to `2.x` because master will break Backward compatibility.
Branch `1.x` will be used to keep backward compatibility for existing projects using this.

**Comment by BernardoSilva** [comment]
:+1: for making it clear and looking cool. :sunglasses:

**Comment by amyboyd** [comment]
This competes #2 so merging to test Travis.

**Pull request merged**
